#!/usr/bin/env python
# coding: utf-8

'''
Turtle starter code
ATLS 1300
Author: Dr. Z
Author: Victor Alamillo
September 8, 2021
'''

import turtle #import the library of commands that you'd like to use

turtle.colormode(255)

# Create a panel to draw on. 
panel = turtle.Screen()
w = 750 # width of panel
h = 750 # height of panel
panel.setup(width=w, height=h) #600 x 600 is a decent size to work on. 
#You can experiment by making it the size of your screen or super tiny!

# Create a colorful background and add Bezos image to it
image = "Bezos.gif"
panel.bgcolor("lightsteelblue1")
panel.bgpic(image)

#=======Add your code here======
turtle.speed(10)
turtle.penup()
turtle.goto(-17,106)
turtle.pendown()
turtle.pencolor("gray30")
turtle.fillcolor("red")
turtle.pensize(4)
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(40,110)
turtle.pendown()
turtle.pencolor("red")
turtle.circle(10)
turtle.penup()
turtle.goto(-225,-40)
turtle.pendown()
turtle.pencolor("black")
turtle.fillcolor("DarkGray")
turtle.pensize(10)
turtle.begin_fill()
turtle.left(25)
turtle.forward(165)
turtle.right(65)
turtle.forward(95)
turtle.left(70)
turtle.forward(60)
turtle.right(65)
turtle.forward(145)
turtle.right(50)
turtle.forward(167)
turtle.right(95)
turtle.forward(372)
turtle.right(90)
turtle.forward(20)
turtle.right(60)
turtle.forward(175)
turtle.right(35)
turtle.forward(92)
turtle.left(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(11)
turtle.left(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(14)
turtle.left(90)
turtle.forward(32)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(15)
turtle.left(90)
turtle.forward(100)
turtle.left(28)
turtle.forward(265)
turtle.right(102)
turtle.forward(100)
turtle.right(39)
turtle.forward(40)
turtle.end_fill()
turtle.penup()
turtle.goto(-190,-224)
turtle.right(33)
turtle.pendown()
turtle.pencolor("black")
turtle.fillcolor("DarkGray")
turtle.pensize(10)
turtle.begin_fill()
turtle.forward(170)
turtle.left(75)
turtle.forward(40)
turtle.left(100)
turtle.forward(190)
turtle.left(100)
turtle.forward(65)
turtle.end_fill()
turtle.penup()
turtle.goto(-90,120)
turtle.pendown()
turtle.begin_fill()
turtle.left(63)
turtle.forward(150)
turtle.left(90)
turtle.forward(45)
turtle.left(50)
turtle.forward(90)
turtle.left(60)
turtle.forward(85)
turtle.left(65)
turtle.forward(73)
turtle.end_fill()
turtle.penup()
turtle.goto(-23,235)
turtle.pendown()
turtle.left(180)
turtle.pensize(7)
turtle.forward(30)
turtle.penup()
turtle.goto(-10,265)
turtle.pendown()
turtle.pencolor("DodgerBlue3")
turtle.fillcolor("DarkOrange1")
turtle.pensize(6)
turtle.begin_fill()
turtle.circle(15)
turtle.end_fill()
turtle.penup()
turtle.goto(119,-85)
turtle.right(115)
turtle.pendown()
turtle.pencolor("red1")
turtle.pensize(12)
turtle.forward(300)
#=======Clean up code (do not change)======
# this code ensures that your script runs correctly each time.
turtle.done()
